import React, { Component } from 'react';
import firebase from 'firebase';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Button,
  TextInput,
  ListView,
  ScrollView
} from 'react-native';
 //import {NotificationsAndroid} from 'react-native-notifications';
 

class Posts extends Component {
    constructor () 
    {
        super()
        this.state = {
            postMessage: ''
        };
        const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        this.messages = [];
        this.dataSource = ds.cloneWithRows(this.messages);
        this.handleInputOnChange = this.handleInputOnChange.bind(this);
        this.getAllPosts((message) => {
                this.messages.push(message);
                this.dataSource = ds.cloneWithRows(this.messages);
                this.handleInputOnChange = this.handleInputOnChange.bind(this);
                
                this.forceUpdate();
        });/*
        var PushNotification = require('react-native-push-notification');
        
    PushNotification.configure({

        onRegister: function(token) {
            console.log( 'TOKEN:', token );
        },
        onNotification: function(notification) {
            console.log( 'NOTIFICATION:', notification );
        },
        permissions: {
            alert: true,
            badge: true,
            sound: true
        },
        popInitialNotification: true,
        requestPermissions: true,
    });
        PushNotification.localNotificationSchedule({
            message: "My Notification Message", // (required)
            date: new Date(Date.now() + (5 * 1000)) // in 60 secs
        });
       NotificationsAndroid.setRegistrationTokenUpdateListener((deviceToken) => {
            console.log('Push-notifications registered!', deviceToken)
        });
        NotificationsAndroid.localNotification({
            title: "Local notification",
            body: "This notification was generated by the app!",
            extra: "data"
        });
        */
    }

    saveBBDD (typeName)
    {
        const itemToSave = {userId: 1, postText: this.state.postMessage};
        const dbRef = firebase.database().ref(typeName);
        const newItemToSave = dbRef.push();
        newItemToSave.set(itemToSave);
    }

    getAllPosts(callback)
    {
        firebase.database().ref('post').on('child_added', function(data) {
            callback(data.val().postText);
        });
    }

    handleInputOnChange (event){
        this.setState({
            postMessage: event.target.value
        });
    }

    renderPostButton(){
        return (<Button onPress={() => this.saveBBDD('post')} title="Post message"/>)
    }

    render () 
    {
        return (
        <View>
            <View>
                <TextInput id="inputMessage" onChangeText={(postMessage) => this.setState({postMessage})}/>
                {this.renderPostButton()}
            </View>
            <ListView 
            dataSource={this.dataSource}
            renderRow={(rowData) => <Text>{rowData}</Text>}
            />
        </View>
        )
    }
}
export default Posts;
